### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class io.circe.Decoder$ after Shading

### ISSUE THREAD

**Issue by clintoncheang** [sbt/sbt-assembly#465]
Hi all, I tried to shade shapeless when I did a spark-submit using sbt-assembly. In my Spark Assembly scala file, I added `assembly / assemblyShadeRules := Seq(ShadeRule.rename("shapeless.**" -> "new_shapeless.@1").inAll)`. But when I submit it to Spark 3.1.2, I got this error above. I am wondering am I adding the Shading correctly?

**Comment by dmykhailov** [comment]
Same here. Have you found any solution so far?

**Comment by joan38** [comment]
Same here when I try to upgrade to Spark 3.x. Works fine on Spark 2.4.4

**Comment by mattharder91** [comment]
Possibly related to this issue:

[https://github.com/typelevel/cats/issues/3628](https://github.com/typelevel/cats/issues/3628)

my issue was that circe had a different version of cats than spark 3

shading should help:

`assembly / assemblyShadeRules := Seq(
        ShadeRule.rename("shapeless.**" -> "new_shapeless.@1").inAll,
        ShadeRule.rename("cats.kernel.**" -> s"new_cats.kernel.@1").inAll
      ),`
